// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);




wire rst_n, pll_rst;
wire sys_clk, spi_clk, pll_locked;
wire[7:0] rd_data;
wire req,ack;

wire[5:0] address;

wire spi_oe;
wire spi_data;

//Initial setup
wire rw;//Read/Write
wire[7:0] wdata;//Writedata

wire signed[9:0] accx;
wire signed[9:0] accy;

wire        row_normal;
wire [3:0]  col_normal;

wire        row_test;
wire [3:0]  col_test;

wire        row;
wire [3:0]  col;


assign GSENSOR_SDI= spi_oe ? spi_data : 1'bz;
assign rst_n=KEY[0];
assign pll_rst=~KEY[0];
assign LEDR[9:0] = accx;







pll pll_inst(
	.areset ( pll_rst       ),
	.inclk0 ( MAX10_CLK1_50 ),
	.c0     ( sys_clk       ),
	.c1     ( spi_clk       ),
	.c2     ( vga_clk       ),
	.locked ( pll_locked    )
	);


spi_phy  spi(
    .rst_ni    ( rst_n   ),
    .clk_i     ( sys_clk ),  
    .spi_clk_i ( spi_clk ), 

  
    .req_i     ( req        ),
    .rw_ni     ( rw         ),  
    .addr_i    ( address    ),
    .wr_data_i ( wdata      ),
    .ack_o     ( ack        ),
    .rd_data_o ( rd_data    ),

    
    .spi_cs_no  ( GSENSOR_CS_N ),
    .spi_clk_o  ( GSENSOR_SCLK ),
    .spi_data_o ( spi_data     ),
    .spi_data_i ( GSENSOR_SDI  ),
    .spi_oe_o   ( spi_oe       )      
);


req_ack_phy miniprocesor(
    .clk_i     ( sys_clk ),
    .rst_ni    ( rst_n   ),

    .req_o     ( req     ),
    .rw_o      ( rw      ),
    .address_o ( address ),
    .wr_data_o ( wdata   ),
    .ack_i     ( ack     ),
    .rd_data_i ( rd_data ),

    .accx_o    ( accx ),
    .accy_o    ( accy )

);

acc_2_rowcol converter(
	.clk_i  ( sys_clk ),
	.rst_ni ( rst_n   ),
	
	.accx_i ( accx ),
	.accy_i ( accy ),
	
	.row_o ( row ),
	.col_o ( col )
	

);


hex_displays_animated dut(
    .clk_i  ( sys_clk ),
    .rst_ni ( rst_n   ),
    .row_i  ( row     ),
	 .col_i  ( col     ),
    .hex_o  ( {HEX5,HEX4,HEX3,HEX2,HEX1,HEX0} )
);


wire [3:0]red,green,blue;
wire video_on;
wire[9:0]pixel_x;
wire[9:0]pixel_y;
wire vga_clk;


vga_driver vga(
		.clk_i  ( vga_clk ),
      .rst_ni ( rst_n   ),

		.rgb_ri ( red   ),
		.rgb_gi ( green ),
		.rgb_bi ( blue  ),
		
		.VGA_Ro ( VGA_R ),
		.VGA_Go ( VGA_G ),
		.VGA_Bo ( VGA_B ),
		
		.VGA_HSo ( VGA_HS ),
		.VGA_VSo ( VGA_VS ),
		
		.pixel_xo  ( pixel_x  ),
		.pixel_yo  ( pixel_y  ),
		.video_ono ( video_on )

);

rgb_generator rgb(
	.pixel_xi  ( pixel_x  ),
	.pixel_yi  ( pixel_y  ),
	.video_oni ( video_on ),

	.accx_i ( accx ),
	.accy_i ( accy ),
	
	.rgb_ro ( red   ),
   .rgb_go ( green ),
   .rgb_bo ( blue  )
	
);


endmodule
